Controllers/CourseController.cs
using LoginAndCRUDCoreProject.Models;
using LoginAndCRUDCoreProject.ViewsModels;
using LoginAndCRUDCoreProject.Services;
using Microsoft.AspNetCore.Mvc;
using LoginAndCRUDCoreProject.DTO;

namespace LoginAndCRUDCoreProject.Controllers
{
    public class CourseController : Controller
    {
        public readonly ICourseService _courseService;
        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }

        [HttpGet("/courseList")]
        public async Task<IActionResult> CourseList()
        {
            return View(await _courseService.doGetCourseList());
        }
        public async Task<IActionResult> CreateCourse()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCourse(CourseVM coursevm)
        {
            if(ModelState.IsValid)
            {
                CourseDto courseDto = new CourseDto();
                courseDto.CourseName = coursevm.CourseName;
                courseDto.Fees = coursevm.Fees;
                courseDto.Duration = coursevm.Duration;
                _courseService.doAddCourse(courseDto);
                return RedirectToAction(nameof(CourseList));
            }
            return View("CourseCreate", coursevm);
        }

        public ActionResult UpdateCourse(int id)
        {
            Course course = _courseService.doGetCourseById(id);
            CourseDto courseDto = new CourseDto();
            courseDto.CourseId = course.CourseId;
            courseDto.CourseName =course.CourseName;
            courseDto.Fees = course.Fees;
            courseDto.Duration = course.Duration;
            return View(courseDto);
        }

        [HttpPost]
        public ActionResult UpdateCourse(int id, CourseDto courseDto)
        {
            if (ModelState.IsValid)
            {
                _courseService.doUpdateCourse(courseDto);
                return RedirectToAction(nameof(CourseList));
            }
            return View(courseDto);
        }

        [HttpPost]
        public ActionResult DeleteCourse(int id)
        {
            var course = _courseService.doGetCourseById(id);
            _courseService.doDeleteCourse(course);
            return RedirectToAction(nameof(CourseList));
        }
    }
}

Controllers/StudentController.cs
using LoginAndCRUDCoreProject.Data;
using LoginAndCRUDCoreProject.DTO;
using LoginAndCRUDCoreProject.Models;
using LoginAndCRUDCoreProject.Services;
using LoginAndCRUDCoreProject.ViewsModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LoginAndCRUDCoreProject.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly UserManager<User> _userManager;

        public StudentController(IStudentService studentService, UserManager<User> userManager)
        {
            _studentService = studentService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        { 
           return View(await _studentService.doGetStudentList());
        }

        //[Authorize(Policy = "RequireAdministratorRole")]
        //public IActionResult AddOrEdit(int id=0)
        //{
        //    if (id == 0)
        //    {
        //        return View(new Student());
        //    }
        //    else
        //    {
        //        return View(_studentService.doGetStudentById(id));
        //    }
        //}

        //[Authorize(Policy = "RequireAdministratorRole")]
        public async Task<IActionResult> CreateStudent()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateStudent(StudentVM studentVM)
        {
            //private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
            var userId = _userManager.GetUserId(User);
            if (ModelState.IsValid)
            {
                StudentDto studentDto = new StudentDto();
                studentDto.Name = studentVM.Name;
                studentDto.Email = studentVM.Email;
                studentDto.Address = studentVM.Address;
                studentDto.UserId = userId;
                _studentService.doAddStudent(studentDto);

                return RedirectToAction(nameof(Index));
                //return View("/courseList");
            }
            return View("CreateStudent", studentVM);
        }

        //[Authorize(Policy = "RequireAdministratorRole")]
        public ActionResult UpdateStudent(int id)
        {
            Student student = _studentService.doGetStudentById(id);
            StudentDto studentDto = new StudentDto();
            studentDto.StudentId = student.StudentId;
            studentDto.Name = student.Name;
            studentDto.Email = student.Email;
            studentDto.Address = student.Address;
            return View(studentDto);
        }

        [HttpPost]
        public ActionResult UpdateStudent(int id, StudentDto studentDto)
        {
            if (ModelState.IsValid)
            {
                _studentService.doUpdateStudent(studentDto);
                return RedirectToAction(nameof(Index));
            }
            return View(studentDto);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteStudent(int id)
        {
            var studentById = _studentService.doGetStudentById(id);
            _studentService.doDeleteStudent(studentById);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LoginAndCRUDCoreProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LoginAndCRUDCoreProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">LoginAndCRUDCoreProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("Admin"))
                            {
                                @*<li class="nav-item">
                                    <div class="ui dropdown item">
                                        <a asp-controller="Course" asp-action="CourseList">Courses</a>
                                        <div class="menu">
                                            <a asp-controller="Course" asp-action="CreateCourse">Create Course</a>
                                        </div>
                                    </div>
                                </li>*@
                                <li class="nav-item">
                                    <div class="dropdown">
                                        <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Courses
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="Course" asp-action="CreateCourse">Create Course</a></li>
                                            <li><a class="dropdown-item" asp-controller="Course" asp-action="CourseList">Course List</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <div class="dropdown">
                                        <button class="btn dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            Students
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" asp-controller="Student" asp-action="CreateStudent">Create Student</a></li>
                                            <li><a class="dropdown-item" asp-controller="Student" asp-action="Index">Student List</a></li>
                                        </ul>
                                    </div>
                                </li>
                                @*<li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Dropdown
                                    </a>
                                    <ul class="dropdown-menu dropdown-menu-dark">
                                        <li><a class="dropdown-item" href="#">Action</a></li>
                                        <li><a class="dropdown-item" href="#">Another action</a></li>
                                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    </ul>
                                </li>*@
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LoginAndCRUDCoreProject - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>